
// DEFINIENDO LAS ACCIONES QUE SE REALIZAN EN API POSTS
export const OBTENER_POSTS = 'OBTENER_POSTS'
export const OBTENER_POST = 'OBTENER_POST'
export const NUEVO_POST = 'NUEVO_POST'
export const EDITAR_POST = 'EDITAR_POST'
export const ELIMINAR_POST = 'ELIMINAR_POST'
export const ERROR_CONSULTA = 'ERROR_CONSULTA'
export const LIMPIAR_POST = 'LIMPIAR_POST'